In [9]:
import numpy as np
import matplotlib as plt
def draw_dashboard():
    chaseboard=np.zeros((8,8),dtype=int)
    chaseboard[1::2, ::2]=1
    chaseboard[::2,1::2]=1
    
    plt.figure(figsize=(4,4))
    plt.imshow(chaseboard,cmap='gray',interpolation='nearest')
    

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
